title: Minimal
baseurl: ""
url: https://minimal.ruoyu.io

tagline: Minimal | A minimalist Jekyll blog theme.
description: >-
  A minimalist Jekyll blog theme.
# logo: /assets/images/logo.png
author: Zhong Ruoyu
copyright:
  years: 2022
  owner: Zhong Ruoyu

lang: en
locale: en_GB
date_format: "%e %B %Y"

seo: true
# google_analytics: G-##########

navigation_items:
  - name: Blog
    path: /blog/
  - name: Projects
    path: /projects/
  - name: About
    path: /about/

future: true
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: page

sass:
  sourcemap: development

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
