title: Minimal
baseurl: /minimal
url: https://zhongruoyu.github.io

tagline: Minimal | A minimalist Jekyll blog template.
description: >-
  A minimalist Jekyll blog template.
# logo: /assets/images/logo.png
author: Zhong Ruoyu
copyright:
  years: 2022
  owner: Zhong Ruoyu

lang: en
locale: en_GB
date_format: "%e %B %Y"

seo: true

navigation_items:
  - name: Blog
    path: /blog/
  - name: Projects
    path: /projects/
  - name: About
    path: /about/

defaults:
  - scope:
      path: ""
    values:
      layout: page

sass:
  sourcemap: development

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
