title: Minimal
baseurl: /minimal
url: https://zhongruoyu.github.io

lang: en
locale: en_US

tagline: Minimal | A minimalist Jekyll blog template.
description: >-
  A minimalist Jekyll blog template.
# logo: /assets/images/logo.png
author: Zhong Ruoyu
copyright:
  years: 2022
  owner: Zhong Ruoyu

seo: true
sitemap: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

sass:
  sourcemap: development

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
